### ISSUE TITLE
BrowserModule has already been loaded

### ISSUE THREAD

**Issue by OxyMonster** [milantenk/ngx-interactive-paycard#28]
Please remove BrowserModule import from the library, I use the lazy loading module and I can't remove BrowserModule import from my root module, it will mess the things.  

see error below  -----> 

ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

**Comment by milantenk** [comment]
Hi OxyMonster,
thanks for the remark, I'm going to take a look at it at the weekend.

**Comment by milantenk** [comment]
Resolved in #29. The 2.0.1 version contains the fix.
https://www.npmjs.com/package/ngx-interactive-paycard/v/2.0.1
