### ISSUE TITLE
Use translated label strings from an optional parameter

### ISSUE THREAD

**Issue by milantenk** [milantenk/ngx-interactive-paycard#3]
Currently the library has hard coded label string in English language. This is problematic, if someone would use the library in an other language context.

The requirement is to get these label strings as optional parameter in the library. The library should contain the original strings as default value, and if there are optional translated parameters, the form should display those.

When the implementation is finished, the README files should be updated with the new parameter.

**Comment by Villanuevand** [comment]
Hi @milantenk  I would like to take this issue... 

Could you assign it to me?

**Comment by milantenk** [comment]
Sure @Villanuevand, it is yours. :)

**Comment by Villanuevand** [comment]
@milantenk Thanks...
Nice project BTW!

**Comment by milantenk** [comment]
Thank you! 😄

**Comment by milantenk** [comment]
I just merged the PR and created `1.1.0` version that contains the new feature. The package is deployed [here](https://www.npmjs.com/package/ngx-interactive-paycard) to npm.js. Thank you for your contribution! 😄

**Comment by Villanuevand** [comment]
> I just merged the PR and created `1.1.0` version that contains the new feature. The package is deployed [here](https://www.npmjs.com/package/ngx-interactive-paycard) to npm.js. Thank you for your contribution! 😄

Im happy to help @milantenk 
If do you have a release plan for future features o enhancements o wherever to enhance the project, Feel free to ping me up! 

I love this project...

**Comment by milantenk** [comment]
Okok, thank you! :)
